SELECT 
    RR.REST_ID
    , RI.REST_NAME
    , RI.FOOD_TYPE
    , RI.FAVORITES
    , RI.ADDRESS
    , ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW RR
LEFT OUTER JOIN REST_INFO RI
    ON RI.REST_ID = RR.REST_ID
GROUP BY RR.REST_ID
HAVING RI.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, RI.FAVORITES DESC;