-- 코드를 입력하세요
SELECT FH.FLAVOR AS FLAVOR
FROM FIRST_HALF FH
INNER JOIN ICECREAM_INFO II ON II.FLAVOR = FH.FLAVOR
    AND II.INGREDIENT_TYPE = 'fruit_based'
WHERE FH.TOTAL_ORDER > 3000
ORDER BY FH.TOTAL_ORDER DESC;